fix: simplify
Signed-off-by: martabal <74269598+martabal@users.noreply.github.com>

diff --git a/root/usr/local/bin/immich b/root/usr/local/bin/immich
--- a/root/usr/local/bin/immich
+++ b/root/usr/local/bin/immich
@@ -1,4 +1,34 @@
-#!/bin/sh
-echo "To execute the administrative CLI, run 'immich-admin'"
-echo "To execute the CLI for uploading assets, run 'immich-upload'"
-echo "To update the CLI for uploading assets, run 'immich-upload-update'"
+#!/usr/bin/with-contenv bash
+
+if [[ $# -eq 0 ]]; then
+    echo "Usage: immich [upload|reset-admin-password|enable-password-login|disable-password-login|list-users|help]"
+    exit 1
+fi
+
+case $1 in
+upload)
+    node /app/cli/bin/index.js "$@"
+    ;;
+reset-admin-password | enable-password-login | disable-password-login | list-users)
+    node /app/immich/server/dist/main cli "$@"
+    ;;
+help)
+    shift
+    case $1 in
+    upload)
+        node /app/cli/bin/index.js help
+        ;;
+    admin)
+        node /app/immich/server/dist/main cli help
+        ;;
+    *)
+        echo "Invalid command for help. Available commands are: admin, upload"
+        exit 1
+        ;;
+    esac
+    ;;
+*)
+    echo "Invalid command. Please refer to the help: immich help [admin|upload]"
+    exit 1
+    ;;
+esac
